trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: varGroup

steps:
- task: Cache@2
  displayName: Cache
  inputs:
    key: 'npm | "$(Agent.OS)" | $(system.defaultWorkingDirectory)/package-lock.json'
    path: '$(system.defaultWorkingDirectory)/node_modules'
    cacheHitVar: CacheRestored

- script: |
   npm install
  workingDirectory: $(system.defaultworkingdirectory)

- script: |
   node export.js
  workingDirectory: $(system.defaultworkingdirectory)
